# Generated by Django 2.1.4 on 2019-01-09 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nutrition_score', models.CharField(max_length=10)),
                ('url_img_small', models.URLField(null=True)),
                ('url_img_big', models.URLField(null=True)),
                ('carbohydrates_100g', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('carbohydrates_unit', models.CharField(max_length=10, null=True)),
                ('proteins_100g', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('proteins_unit', models.CharField(max_length=10, null=True)),
                ('energy_100g', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('energy_unit', models.CharField(max_length=10, null=True)),
                ('sodium_100g', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('sodium_unit', models.CharField(max_length=10, null=True)),
                ('fiber_100g', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('fiber_unit', models.CharField(max_length=10, null=True)),
                ('sugars_100g', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('sugars_unit', models.CharField(max_length=10, null=True)),
                ('saturatedfat_100g', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('saturatedfat_unit', models.CharField(max_length=10, null=True)),
                ('fat_100g', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('fat_unit', models.CharField(max_length=10, null=True)),
                ('salt_100g', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('salt_unit', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('id_aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_aliment', to='compte.Aliment')),
                ('id_aliment_substitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_aliment_substitution', to='compte.Aliment')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='substitution',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.Account'),
        ),
        migrations.AddField(
            model_name='aliment',
            name='id_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.Categorie'),
        ),
    ]
